### ISSUE TITLE
ok...(title too long)

### ISSUE THREAD

**Issue by sindresorhus** [silverbux/bootflat-admin#1]
@silverbux keeps deleting comments. This is what the discussion looked like: https://cloud.githubusercontent.com/assets/170270/12801328/7473bb14-cb0e-11e5-8e24-850d0aa58ba9.png

**Comment by silverbux** [comment]
just wondering what would happen, sorry if it annoyed you. ok stoping now ^^

**Comment by Qix-** [comment]
Just going to report people like this from now on.

**Comment by silverbux** [comment]
i am not promoting it, you could check the commits, its almost 2 years now since i updated the project, it seems to be a trend and i also getting lot of it in my timeline and just checked it jeezz..

**Comment by Qix-** [comment]
Then why are you adding users to your repositories and changing titles of issues?

**Comment by silverbux** [comment]
i see you're new here, it's internet dude, i was just trollin. omg you guys are too serious..
and is it wrong to say that somehow i was hoping for them to contribute on a dead project?

**Comment by Qix-** [comment]
Yes. They have hundreds upon hundreds of other repositories and hundreds upon hundreds of issues they have to take care of _every day_. They don't need a repository they don't care about cluttering up their notifications.

Definitely not new here, for the record. I just have a problem with people abusing the community.

**Comment by silverbux** [comment]
dude look, its an open source admin template, im not gonna gain any money from it. 
"abusing" i just used an existing feature of github that's let you add collaborators, 
if your up for it maybe be best to create a repo like https://github.com/dear-github/dear-github to not show notifications like that in their timeline or have an option for it.

**Comment by Qix-** [comment]
Or how about you just stop abusing the community and unprotected features of an otherwise very clean and honest site?

That works too.

**Comment by silverbux** [comment]
alright :+1:

**Comment by seiyria** [comment]
Or just don't do this. It's incredibly rude to those people who have far better things to do than deal with this, especially because of how inconvenient it is for them to now have to go manually unsubscribe from everything.

**Comment by sindresorhus** [comment]
> "abusing" i just used an existing feature of github that's let you add collaborators

Slapping someone is just using an existing feature of the hand. 😣🌴

**Comment by Qix-** [comment]
Also, stop deleting my comments @silverbux. Fucking annoying.

**Comment by GeerSwitch** [comment]
+1 for Qix. This is an absurd waste of time for those "graciously" added as "collaborators".

**Comment by silverbux** [comment]
1.) as i said it's a dead project, why promote it.

2.) @sindresorhus you twitted about it and now twitter.com is the second source of traffic next to github.com... "promotion"

3.) please look at the following, sometimes im just curious about things no matter how foolish they are. perhaps this time i gone too far. i did not realize it would escalate.

https://github.com/silverbux/rsjs
    - this repo implements a script similar to this https://github.com/gelstudios/gitfiti ( forgot the exact repo i used )
        - it fills up your github contribution graphs

https://github.com/silverbux/rsjs/commits/master
    - checkout the last 3 commits, a github glitch where you could use other profile as committer.
        - tried this the second i saw an article about it.

4.) here's an email from a random stranger. some before this even escalated some after just check date time im at GMT+/--8:00. 
    - http://ligi.de on his signature, contact him if you want authenticity of screenshot.

<img width="738" alt="email2" src="https://cloud.githubusercontent.com/assets/1888261/12807251/ad14f2be-cb48-11e5-818d-9f49a7a7b211.png">

<img width="740" alt="email1" src="https://cloud.githubusercontent.com/assets/1888261/12807513/99491218-cb4a-11e5-9c7e-ba84ef6e6670.png">

**Again i apologise for any inconvenience that this may have caused you.**

**Comment by silverbux** [comment]
there used to be a saying here "break the internet", but i guess its about the stars now.
(just saying)

**Comment by justinhelmer** [comment]
> https://github.com/silverbux/rsjs/commits/master
- checkout the last 3 commits, a github glitch where you could use other profile as committer.
- tried this the second i saw an article about it.

Just so wrong in so many ways. Furthest thing from a justification.

**Comment by silverbux** [comment]
please read it fully, by copy pasting just 2 lines, its giving it a diffrent meaning. and im not saying it justify the action.

**Comment by egoist** [comment]
That's why here's another feature: Block user (exactly like @silverbux) on GitHub.
